demo_model:
  demo_position_controller:
    type: position_controllers/JointPositionController
    joint: link_A_to_link_B
    pid: {p: 100.0, i: 0.01, d: 10.0}

  demo_effort_controller:
    type: effort_controllers/JointPositionController
    joint: link_A_to_link_B
    pid: {p: 100.0, i: 0.01, d: 10.0}
